name: setup-hacklang
description: Install HHVM and set up the Hack programming language environment
author: CodeWithSushil
inputs:
  hhvm-version:
    description: The version of HHVM/Hack to install
    required: true
    default: latest

branding:
  icon: 'code'
  color: purple

runs:
  using: composite
  steps:
    - name: Install HHVM
      run: |
        set -euxo pipefail

        sudo apt-get update
        sudo apt-get install -y curl gnupg lsb-release ca-certificates composer php

        sudo mkdir -p /usr/share/keyrings

        curl -fsSL https://dl.hhvm.com/conf/hhvm.gpg.key | \
        gpg --dearmor | sudo tee /usr/share/keyrings/hhvm.gpg > /dev/null

        DISTRO=$(lsb_release -cs)
        echo "deb [signed-by=/usr/share/keyrings/hhvm.gpg] https://dl.hhvm.com/ubuntu ${DISTRO} main" | \
        sudo tee /etc/apt/sources.list.d/hhvm.list
        sudo apt-get update
        sudo apt-get install -y hhvm

        hhvm --version
