name: setup-hacklang
description: Install HHVM and set up the Hack programming language environment
author: sushil
inputs:
  hack-version:
    description: The version of HHVM/Hack to install
    required: true
    default: latest
  debug:
    description: Code Debugging
    required: false
    default: false
    
branding:
  icon: 'code'
  color: purple

runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/scripts/composer.sh

    - shell: bash
      run: |
        sudo apt-get update
        dpkg --print-architecture
        sudo apt-cache policy hhvm
        sudo apt search hhvm
