on: [push]

jobs:
  example:
    runs-on: ubuntu-22.04


    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: setup-hacklang
        uses: CodeWithSushil/setup-hhvm@1.2.3 
      - name: Inspect
        run: |
          php --version
          composer --version
          hhvm --version
          hh_client --version

      - name: Running hack script
        run: hhvm examples/index.hack
